name: Generate release artifacts

on:
  workflow_dispatch:
    inputs:
      release:
        description: Add artifacts to release
        required: false
        default: true
  release:
    types: [published]

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Pre-build binaries
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - uses: actions/checkout@v2.3.3
      - name: Get latest tag
        id: latesttag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Make directory for binaries
        run: mkdir bin
      - name: Build Windows x86
        env:
          GOOS: windows
          GOARCH: "386"
        run: go build -o bin/snakep2p.${{ steps.latesttag.outputs.tag }}.windows-386.exe ./cmd/snakep2p
      - name: Build Windows x86_64
        env:
          GOOS: windows
          GOARCH: amd64
        run: go build -o bin/snakep2p.${{ steps.latesttag.outputs.tag }}.windows-amd64.exe ./cmd/snakep2p
      - name: Build Linux x86
        env:
          GOOS: linux
          GOARCH: "386"
        run: go build -o bin/snakep2p.${{ steps.latesttag.outputs.tag }}.linux-386 ./cmd/snakep2p
      - name: Build Linux x86_64
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build -o bin/snakep2p.${{ steps.latesttag.outputs.tag }}.linux-amd64 ./cmd/snakep2p
      - name: Build Mac OS X
        env:
          GOOS: darwin
          GOARCH: amd64
        run: go build -o bin/snakep2p.${{ steps.latesttag.outputs.tag }}.darwin-amd64 ./cmd/snakep2p
      - name: Upload artifacts to job
        uses: actions/upload-artifact@v2
        with:
          name: snakep2p-bin
          path: bin/
      - name: Create release
        uses: Roang-zero1/github-create-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifacts to release
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          args: bin/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
